language: python

python:
  - "3.7"

# command to install dependencies
install:
  - make init

services:
  - docker

before_install:
  - docker pull johnklee/atf_docker_test2:latest

# command to run tests
script:
  - make test
